const majors = [
    'Africana Studies',
    'Agricultural Sciences',
    'American Studies',
    'Animal Science',
    'Anthropology',
    'Applied Economics and Management',
    'Archaeology',
    'Architecture',
    'Asian Studies',
    'Astronomy',
    'Atmospheric Science',
    'Biological Engineering',
    'Biological Sciences',
    'Biology and Society',
    'Biomedical Engineering',
    'Biometry and Statistics',
    'Chemical Engineering',
    'Chemistry and Chemical Biology',
    'China and Asia-Pacific Studies',
    'Civil Engineering',
    'Classics',
    'Cognitive Science',
    'Communication',
    'Comparative Literature',
    'Computer Science',
    'Design and Environmental Analysis',
    'Earth and Atmospheric Sciences',
    'Economics',
    'Electrical and Computer Engineering',
    'Engineering Physics',
    'English',
    'Entomology',
    'Environment and Sustainability',
    'Environmental Engineering',
    'Fashion Design and Management',
    'Feminist, Gender, and Sexuality Studies',
    'Fiber Science',
    'Fine Arts',
    'Food Science',
    'French',
    'German Studies',
    'Global and Public Health Sciences',
    'Global Development',
    'Government',
    'Health Care Policy',
    'History',
    'History of Architecture',
    'History of Art',
    'Hotel Administration',
    'Human Biology, Health, and Society',
    'Human Development',
    'Industrial and Labor Relations',
    'Information Science',
    'Information Science, Systems, and Technology',
    'Italian',
    'Jewish Studies',
    'Landscape Architecture',
    'Linguistics',
    'Materials Science and Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Music',
    'Near Eastern Studies',
    'Nutritional Sciences',
    'Operations Research and Engineering',
    'Performing and Media Arts',
    'Philosophy',
    'Physics',
    'Plant Sciences',
    'Psychology',
    'Public Policy',
    'Religious Studies',
    'Science and Technology Studies',
    'Sociology',
    'Spanish',
    'Statistical Science',
    'Urban and Regional Studies',
    'Viticulture and Enology'
]

export default majors
