name: CI Policies
on: pull_request

jobs:
  warn-big-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: cornell-dti/big-diff-warning@main
        env:
          BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
