name: CI Policies
on: pull_request

jobs:
  warn-big-diff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: cornell-dti/big-diff-warning@master
        env:
          BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
